### ISSUE TITLE
Training Parse Model with torch 1.7.0

### ISSUE THREAD

**Issue by bjascob** [bjascob/amrlib#10]
Looks like the parse model has an issue training with torch 1.7.0.  torch 1.6.0 should work.

Error message when training with torch 1.7.0
Traceback (most recent call last):
  File "./20_Train.py", line 14, in <module>
  File "/home/bjascob/Files/Projects/AMR/012_AMRLib_GitHub/amrlib/models/parse_gsii/trainer.py", line 114, in run_training
    loss.backward()
  File "/home/bjascob/.local/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/bjascob/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [24, 129, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by bjascob** [comment]
Issue (temporarily?) fixed by replacing `chunk` with `unsafe_chunk` in transfomer.py::in_proj_qkv

**Comment by bjascob** [comment]
Complete with release of amrlib 0.2.2
