### ISSUE TITLE
No such file or directory: 'amrlib/data/model_sto'

### ISSUE THREAD

**Issue by 141forever** [bjascob/amrlib#68]
Hello！
I tried to run your Library Usage or Usage as a Spacy Extension.
But it comes an error.

------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/test.py", line 2, in <module>
    stog = amrlib.load_stog_model()
  File "/home/hy/miniconda3/envs/1/lib/python3.9/site-packages/amrlib/__init__.py", line 35, in load_stog_model
    stog_model = load_inference_model(model_dir, **kwargs)
  File "/home/hy/miniconda3/envs/1/lib/python3.9/site-packages/amrlib/models/model_factory.py", line 56, in load_inference_model
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), model_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hy/miniconda3/envs/1/lib/python3.9/site-packages/amrlib/data/model_stog'

-----------------------------------------------------------------

**Comment by bjascob** [comment]
Please follow the installation instructions and install the models as described.

**Comment by 141forever** [comment]
THANK YOU, I have worked it out
